Cargo.lock
Cargo.toml
src/cli.rs
src/main.rs
src/scheduler.rs

Just an example of what our celery-beat style task might look like

feat(scheduler): Add simple tokio-cron-scheduler job

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
Dockerfile
src/checker.rs
src/main.rs

Add initial function to perform domain checks. We need better testing around this and probably also need return more useful failure reasons.
I'll follow up later with a pr that adds mocking for the domains so we can test all the cases.

feat: Add function to perform domain checks

---

.github/workflows/test.yml
src/checker.rs
src/main.rs

This adds a lint action for GHA. Also fixes some warnings turned up by clippy, and disables dead code warnings for this crate.

chore: Add clippy and fix some lint warnings

---

Cargo.lock
Cargo.toml
src/scheduler.rs

feat: Execute checker every 5 minutes on sentry.io

---

Dockerfile

This needs to be installed in the build container to fix `Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/uptime-checker`

fix: Fix missing libgcc in docker container

---

Cargo.lock
Cargo.toml
Dockerfile
src/main.rs
src/producer.rs
src/scheduler.rs

This implements the basics of a producer for sending results back to sentry.

feat: Implement basic producer

---

Cargo.lock
Cargo.toml
src/checker.rs
src/producer.rs
src/types.rs

This updates the checker to use `subscription_id` instead of monitor ids

feat(uptime): Update `sentry-kafka-schemas`, remove monitor ids and add subscription_id

---

src/types/check_config.rs

Part of https://github.com/getsentry/uptime-checker/issues/12

ref(config): Add `slots` fn to determine tick slots

---

src/config_store.rs
src/main.rs

Implements the configuration storage / access schema described in https://github.com/getsentry/uptime-checker/issues/12

feat(config): Add ConfigStore to provide access to configs

---

Cargo.lock
Cargo.toml
src/checker.rs
src/cli.rs
src/config_store.rs
src/scheduler.rs

Connects the `ConfigStore` to the scheduler.
The scheduler will now read all `CheckConfig`s at the given tick and create futures to execute each check.
I've also removed the `tokio-cron-scheduler` package in favor of using `tokio`s build in `Interval` to generate our ticks
The example config has now moved the the root cli runner for now

feat: Schedule executions from the ConfigStore

---

src/app.rs
src/config_store.rs
src/scheduler.rs
src/types/check_config.rs

Since we'll be using kafka to store and receive configurations, each config will be part of a kafka partiton. These can be added or removed from the checker during rebalancing, thus we need to support dropping a set of configurations all at once when a partition is removed.
The ConfigStore has learned `drop_partition`, which drops all CheckConfigs associated to a particular partition. It does this efficiently by keeping a TickBuckets list for each partition. When a partition is dropped the entire TickBuckets vector is dropped and all CheckConfigs contained in those buckets are dropped

ref(config-store): Track partitions of configs

---

src/app.rs
src/config_store.rs
src/scheduler.rs

Since we'll be writing from a consumer in a different thread from reading to it, we'll need some synchronization

feat(check-config): Make the store RwLock-able

---

Cargo.lock
Cargo.toml
src/app.rs
src/scheduler.rs

This will actually wait for the last tick to complete before just outright exiting. This does **NOT** wait for the actual checks to complete, only scheduling of them.
In the future we can add some additional logic to make sure an entire tick completes before we fully shut down

feat: Add graceful shutdown of the scheduler via CancellationToken

---

Dockerfile

This was updating packages. We don't actually want that

ref(build): Remove cargo update steps

---

Cargo.lock
Cargo.toml
src/app.rs
src/config_consumer.rs
src/config_store.rs

This adds logic that will wait for the consumer to idle. Once the
consumer is idling we'll know we've read the backlog of configs and can
start the scheduler safely.

feat(consumer): Track 'boot' where it reads the backlog

---

src/config_store.rs
src/types/check_config.rs

If we have multiple values for a subscription in the config topic we will end up with duplicate subscriptions. This pr makes sure that subscriptions won't duplicate when we have an updated config in the topic.
Previously, we decided that since we will always delete/create subscriptions to update them that we didn't need to de-dupe. Due to the way that we generate test configs for the uptime checker this caused a lot of duplicates and confusion with testing. It seems safer to just guarantee that we don't get duplicates.
As well as this, the way we send updates from sentry has an at least once guarantee. So it's possible that we might send the same update more than once in certain failure scenarios. This fix will also guard against this.

fix(uptime): Prevent configs for the same subscription from duplicating

---

src/app.rs
src/config_consumer.rs
src/config_store.rs
src/main.rs
src/manager.rs
src/ready_wait.rs
src/scheduler.rs

Refactors the uptime checker to have a separate scheduler per Kafka partition. This makes assigning/revoking partitions much simpler, and allows us to more easily block while partitions are loading in the future.

Refactor service per partition

---

src/config_consumer.rs
src/types/check_config.rs

`CheckConfig` no longer needs to be aware of which partition it was assigned to, so just removing it.

chore(uptime): Remove partition from `CheckConfig`

---

src/app/config.rs

We're going to use redis to keep track of progress on partitions, so adding config for this

feat(uptime): Add config setting for redis cluster

---

src/config_consumer.rs

We don't want this running as a tokio task since it will block and consume an entire thread. Tokio will only have so many task executor threads so we may end up the scenario where executors are available to drive futures forward.
The reason it was run in a tokio task before was because the partitions update function in the manager would attempt to start new tokio tasks, which it could not do outside of the tokio runtime.
Instead we can use tokios `task::spawn_blocking` to run the consumer, which tokio will run in it's own blocking thread.

fix: Run consumer in it's own thread

---

src/config_waiter.rs
src/main.rs
src/manager.rs

Brings back the logic we wrote to detect when a partition has "completed" booting

feat: Add metrics for each partitions "boot"

---

src/config_consumer.rs
src/manager.rs

There's no reason this field should be mutated so use a getter instead

ref: Add get_partition

---

Cargo.lock
Cargo.toml
src/check_executor.rs
src/main.rs
src/types/result.rs

This adds a new async task that reads from an unbounded mpsc channel and executes checks, firing the oneshot channel when complete.
This will be used in place of the scheduler actually firing off the http checker tasks

feat: Add check_executor

---

src/config_consumer.rs
src/manager.rs

This is mostly helpful in testing so we don't have to use catch_unwind,
which is problematic when the manager contains types that are not
`UnwindSafe` [^1]
[^1]: https://github.com/rust-lang/rfcs/blob/master/text/1236-stabilize-catch-panic.md

ref: Add has_service to manager

---

src/app/config.rs

Adds a `checker_concurrency` setting for the upcoming introduction of a separate check executor (stop dispatching checks from the scheduler, and start actually queueing them from the scheduler)

feat: Add checker_concurrency

---

src/app.rs
src/config_consumer.rs
src/manager.rs

Instead of the manager having "stopped" and "started" state, this makes it so you may ONLY create a manager that is started.
Same for the PartitionedService.
This also makes it easier in the future now to wait for partitioned services to fully stop before the finishing manager shutdown.

ref: Avoid stop / start state in Manager / PartitionedService

---

src/check_executor.rs
src/manager.rs
src/scheduler.rs

Removes the schedulers functionality of actually firing checks and
instead queues checks for execution in the check_executor.
The executor is started when the manager is started.
This allows us to write tests for the scheduler much easier now.

feat: Connect scheduler to check_executor

---

src/check_executor.rs

This isn't very well documented, but the statsd exporter requires the
timer histogram value to be in f64 seconds [^1]
[^1]: https://docs.rs/metrics-exporter-statsd/latest/src/metrics_exporter_statsd/recorder.rs.html#125-131

fix: Correctly record histogram timers as f64 secs

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
src/app/config.rs
src/config_store.rs
src/manager.rs
src/producer/dummy_producer.rs
src/scheduler.rs

This stores tick progress in Redis and loads it when the scheduler starts up. We use this to set the instance that we start from, so that we won't miss ticks during deploys, rebalances and crashes.
We store the ticks as nanos and use them to reset the Interval back in time. We store the completed ticks in `in_order_tick_processor_join_handle`, which gives us a guaranteed in-order completion of ticks, so that we know we're not missing anything.
@wedamija

feat(uptime): Store completed ticks in redis

---

src/config_waiter.rs
src/manager.rs
src/scheduler.rs

We need to wait until all configs are loaded before we start scheduling ticks. Otherwise we end up missing configs due to a race condition between loading configs and processing ticks.

fix(uptime): Make scheduler wait for boot before it starts scheduling ticks

---

src/checker/http_checker.rs
src/producer/kafka_producer.rs
src/types.rs
src/types/check_config.rs
src/types/result.rs
src/types/shared.rs

This updates the http_checker to execute checks using the configurations in the `requets_{method,headers,body}` fields of the `CheckConfig`.

feat(http): Make checks using request configs

---

src/checker/http_checker.rs

We provide 10M spans included in every plan, so it'd take quite a while for uptime to exhaust its quota, even if sending requesting every minute. The value of seeing spans in every uptime trace is higher.

Enable sampling of spans

---

Cargo.lock
Cargo.toml
src/checker/http_checker.rs

Let's enable this and over the legacy hyper Gai resolver. Will deploy to
canary first and make sure everything looks safe

feat(dns): Enable hickory-dns

---

src/checker/http_checker.rs

If the URL included a token or something we wouldn't sanitize it, let's avoid including the URL

ref: Sanitize generic failure error message url

---

src/checker/http_checker.rs
src/types/check_config.rs

part of https://github.com/getsentry/team-uptime/issues/22. will do nothing initially as all uptime trace_sampling values are set to false atm.

feat(uptime): defer sampling if trace_sampling is set to true

---

Cargo.lock
Cargo.toml
src/checker/http_checker.rs
src/types/check_config.rs

bump to latest so we get https://github.com/getsentry/sentry-kafka-schemas/pull/351
part of https://github.com/getsentry/team-uptime/issues/22

feat(uptime): bump sentry kafka schemas to latest

---

src/app/config.rs
src/manager.rs
src/scheduler.rs

This allows region to be specified at the checker level, so that the checker knows where it is running

feat(uptime): Add `region` to the Uptime service config.

---

src/types/check_config.rs
src/types/shared.rs

This adds `active_regions` and `region_schedule_mode` to `CheckConfig` and updates tests. These will be used to schedule checks when multiple regions are present.

feat(uptime): Add region configuration to `CheckConfig`.

---

src/check_executor.rs
src/checker.rs
src/checker/dummy_checker.rs
src/checker/http_checker.rs
src/config_waiter.rs
src/manager.rs
src/producer/kafka_producer.rs
src/scheduler.rs
src/types/result.rs

We need to start returning regions in our results. Also including them in our various stats so that we can break things down by uptime region if necessary

feat(uptime): Add region to uptime results and stats

---

Cargo.lock
Cargo.toml
src/checker/dummy_checker.rs
src/checker/http_checker.rs
src/producer/kafka_producer.rs
src/types/result.rs

We want to ensure that we produce the same ids for the same check. Each scheduled check is uniquely identified via the subscription id and scheduled time. Having these ids be consistent makes it easy for us to de-dupe data if we have duplicates due to a deploy or other issue.

feat(uptime): Make sure result and trace ids are consistent for a scheduled check

---

src/app/config.rs
src/checker/http_checker.rs
src/manager.rs

For self-hosted use cases, we will be checking against private IP address space, most of the times. Since most of the self-hosted deployment are done in a private (and mostly air-gapped) environment.
This PR introduces `allow_internal_ips` on the configuration that hopefully does not break with existing running instances.

feat: allow internal ips for self-hosted instances

---

src/checker/http_checker.rs

we intermittently receive reports that we generate a downtime issue with the decription being `IncompleteMessageError`, and our customers say that their website was in fact up, not down. According to https://github.com/hyperium/hyper/issues/2136, this could be due to connection pooling / a race condition between the client and server. one of the comments suggests setting the connection pool timeout to `0`. https://github.com/hyperium/hyper/issues/2136#issuecomment-861826148
we do not need connection pooling as we aren't making that many requests to one particular host, so there should be no effect, and we can monitor if this fixes the error.

fix: make max_idle_per_host 0

---

src/check_executor.rs
src/manager.rs
src/scheduler.rs

This will allow us to monitor how many checks are being executed concurrently over time. Since we have a concurrency limit this will also help us understand when we're getting close to that limit

feat(metrics): Record queue size of executor as a metric

---

src/check_config_provider.rs
src/check_config_provider/redis_config_provider.rs
src/types/check_config.rs

This adds a `RedisConfigProvider` to manage configs via Redis. We still need to hook this up to the manager, have a way to receive partition assignments, and start monitoring for updates.

feat(uptime): Add `RedisConfigProvider`

---

src/app/config.rs

We'll use these to determine which partitions a checker is assigned.

feat(uptime): Add config values for pod name, total pod count and redis partitions

---

src/app/config.rs
src/check_config_provider/redis_config_provider.rs

This adds `determine_owned_partitions`, which produces a set of partition numbers that this checker owns based on total checkers, total partitions and this checker's checker number.
Simplifies the interface to calling run_config_provider since we can determine partitions via config rather than passing in.

feat(uptime): Add function to determine which partitions a checker owns

---

src/app/config.rs
src/manager.rs

This adds Redis to `ConfigProviderMode` and uses it to start the redis config provider when set.

feat(uptime): Add code to allow manager to start using Redis

---

gocd/templates/bash/deploy.sh

Needed to deploy via gocd, otherwise it won't find the deployment

fix(deploy): Use statefulset deploy

---

src/app/config.rs
src/check_executor.rs
src/manager.rs
src/producer.rs
src/producer/vector_producer.rs

TODO: handle failure modes, determine how to handle if/when vector goes down (should we cap the size of the channel?)

feat: add vector result producer

---

.dockerignore
Dockerfile
cloudbuild.yaml

dev: faster docker builds

---

src/check_config_provider/redis_config_provider.rs

This gets us to parity with how the bootwaiter stores stats

chore(uptime): Add partition number to redis config load stats when appropriate

---

src/app/config.rs
src/checker/http_checker.rs
src/manager.rs

This might be causing problems with our load test in s4s. Just adding this option so we can disable it there.

chore(uptime): Add config to allow us to configure whether to disable connection re-use

---

Cargo.lock
Cargo.toml
src/app/config.rs
src/check_config_provider/redis_config_provider.rs
src/main.rs
src/manager.rs
src/redis.rs
src/scheduler.rs

This implements an option to use the redis cluster client for our redis config provider. Defaults to off for backwards compatibility.

feat(uptime): Implement redis cluster for config checker

---

src/checker/http_checker.rs

we need to remove dashes from the trace_id when we create the trace header. adds assertions on the number of dashes to assure correct format.

fix(uptime): fix trace header format

---

src/scheduler.rs
src/types/check_config.rs

Currently, our checkers in each region are either processing all configs, or are processing none. This pr stripes the work better so that it's evenly distributed between regions

fix(uptime): Fix scheduler to better distribute work amongst the regions

---

src/scheduler.rs

We see some weird spikiness in datadog, trying to determine if it's a stats bug or some kind of scheduling problem.

chore(uptime): Add stat before we filter out skipped region checks

---

Dockerfile.localdev
src/check_executor.rs
src/checker/http_checker.rs
src/types/result.rs

I also considered making `connection_error` split into `connection_reset` and `connection_refused`. thoughts?

feat(uptime): add new failure types

---

.github/workflows/lint.yml
.github/workflows/test.yml
Cargo.lock
Cargo.toml
Dockerfile

needed for new error types in https://github.com/getsentry/uptime-checker/pull/248

fix: bump sentry kafka schemas

---

Dockerfile.localdev
src/check_executor.rs
src/checker/http_checker.rs
src/types/result.rs

This reverts commit f3265a80ccbe1c92c737be65648b26c579f5ca7c.
depends on https://github.com/getsentry/uptime-checker/pull/247

Revert "Revert "feat(uptime): add new failure types (#221)" (#245)"

---

src/scheduler.rs

This fixes a bug that occurs when multiple checkers are competing for the same progress key. If a checker saves the key, and then another boots and gets a value too close to the current time then we end up hitting an `OutOfRangeError` when we subtract `start` from `Utc::Now()`.

fix(uptime): Fix race bug for scheduler progress key

---

src/check_executor.rs

Once an item is running it should be removed from the queue count and added to the running count.

chore(uptime): Improve queue metric

---

src/scheduler.rs

I want to validate the `scheduler.bucket_size` metric, which seems like it's wrong.

chore(uptime): Temporarily set bucket_size log to be `info`

---

src/config_store.rs
src/scheduler.rs
src/types/check_config.rs

Our slot distribution is currently based on the subscription id. The problem with this is that `subscription_id` is already used to partition our configs. This has the side effect of causing configs in a partition to not be distributed evenly among scheduling slots. The result here is that partitions run all at once, then completely stop for a few ticks, then run again, and son on. Using a uuid with a different namespace here will distribute them more evenly.
Some math examples:
Since we modulo subscription ids by 128, then for example, anything that modulos to 51 goes in the same bucket.
For each of those ids in the 51 bucket, if we modulo those by 60 (the number of seconds for an interval), they all map to these numbers
[3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59]
if i do …

fix(uptime): Fix slot distribution to use a `uuid5`

---

Cargo.lock
Cargo.toml

first step of adding more timing telemetry -- let's log dns timing 1% of the time to see if this is impacting timeouts. branch here: https://github.com/getsentry/reqwest-uptime/pull/1

telemtry: log dns timing using fork

---

Cargo.lock
Cargo.toml

hardcodes the revision. and updated the dns log to warn, as that is what our min log level is set in production. https://github.com/getsentry/reqwest-uptime/pull/1/commits/7408a3124f56130a1e89935841ae4314440ef309

feat: hardcode reqwest fork revision

---

Cargo.lock
Cargo.toml

https://github.com/getsentry/reqwest-uptime/pull/1/commits/012bc30a15cead582fc770a1a2ff76bc8c800ae5 100k looks good, not a huge increase in memory, can safely increase to 500k

bump dns cache size to 500k

---

src/check_executor.rs
src/checker/dummy_checker.rs

This will allow us to have results with different status for each
sequential check.

test: Support queuing dummy results in DummyChecker

---

src/app/config.rs
src/check_executor.rs
src/manager.rs
src/scheduler.rs

This adds a new option to allow for retrying failed checks by re-queuing
the check into the executor.
We will continue to record result metrics, but will include a tag
indicating if the result was a retry or not.

feat(executor): Add optional retry for check executor

---

src/manager.rs

this was causing linter errors in CI for some reason. couldn't repro locally but this fixes it https://github.com/getsentry/uptime-checker/actions/runs/13512744201/job/37755946808?pr=267

fix: remove take

---

src/app/config.rs
src/checker/http_checker.rs
src/manager.rs

We disabled connection pooling before because it was causing random failures. Now that we have automated retries, it makes sense to re-enable this. We'd like to also increase the keepalive time so that we can re-use connections for longer.

feat(uptime): Add setting to control how long we keep sockets to servers alive

---

Cargo.lock
Cargo.toml
src/check_executor.rs
src/checker/http_checker.rs
src/types/result.rs

note that we can't deploy this untill a corresponding `redirect_error` has been added to the sentry kafka repo and then the uptime checker, sentry, and snuba have all been bumped with the new version of the library

feat(uptime): add redirect errors

---

Cargo.lock
Cargo.toml
src/app/config.rs
src/check_executor.rs
src/manager.rs

This should help us to understand if our http checker tasks are taking a suspiciously long time to be scheduled or polled.
Our suspicion is that when we turn up execution concurrency we may be overloading the tokio scheduler in a way such that we are very slow to poll the http tasks. By the time we finally poll the task the reqwest timeout may have been reached and the request will be considered timed out.

feat(metrics): Monitor executor task metrics

---

Cargo.lock
Cargo.toml
Dockerfile.localdev
src/checker/http_checker.rs

looking at this https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0A-jsonPayload.message%3D%22scheduler.tick_scheduled%22%0Alabels.%22k8s-pod%2Fservice%22%3D%22uptime-checker%22%0A-%22DNS%22;summaryFields=:true:32:beginning;cursorTimestamp=2025-02-24T22:52:57.665242903Z;duration=PT15S?project=internal-sentry
we can see there are a lot of raw errors making it through. some of them are these hyper_util errors. we need to pin the library from being a sub-dependency so we can use the error here to cast it and return the parsed error.
it looks like there are some ssl errors which can make it into this category, so can follow up to try to separate those. specifically 
```
check_url.error: reqwest::Error { kind: Request, source: …
```

feat: catch hyper util errors

---

Cargo.lock
Cargo.toml
src/app/config.rs
src/checker/http_checker.rs
src/manager.rs

We received advice from google cloud support that we might improve dns lookup times by appending a dot to our hostnames. This implements that.

fix(uptime): Add ability to append a dot to the end of hostnames

---

Cargo.lock
Cargo.toml
src/app/config.rs
src/checker/http_checker.rs
src/manager.rs

This reverts commit e6e6dbd8197422e89b4f8f638a7164396968ed0f.
This did not help and caused more problems than it fixed

Revert "fix(uptime): Add ability to append a dot to the end of hostnames (#262)"

---

src/app.rs
src/app/config.rs

By default tokio allocates one thread per cpu. We're hitting some performance bottlenecks, so testing out allowing more threads per cpu.

feat(uptime): Add ability to configure number of threads per cpu resource

---

Cargo.lock
Cargo.toml
src/app/config.rs
src/checker.rs
src/checker/isahc_checker.rs
src/checker/reqwest_checker.rs
src/manager.rs
src/types/shared.rs

Adds a new Isahc HTTP checker.
We would like to experiment with this checker to collect better metrics
about the HTTP requets being made.
There are a few things we still need to fix before we can enable this
is flakey. See https://github.com/sagebind/isahc/issues/364

feat(http): Implement Isahc HTTP checker

---

Dockerfile

We added this to builder before, but it needs to be in the deploy container

fix(uptime): Add curl to deploy image

---

Cargo.lock
Cargo.toml
src/check_config_provider/redis_config_provider.rs
src/check_executor.rs
src/manager.rs

The executor will block indefinitely until all feeding producers are dropped.  We weren't shutting down the partitioned services when a shutdown was issued, but even with fixing that, the executor still holds on to a producer that it uses for its own retries.  So, just add a `take_until` on the stream, awaiting a future that is triggered by the cancel signal.

fix(uptime): Have uptime-checker shut down gracefully on sigterm

---

src/app.rs
src/app/config.rs
src/check_config_provider/redis_config_provider.rs
src/checker/ip_filter.rs
src/checker/isahc_checker.rs
src/checker/reqwest_checker.rs
src/config_waiter.rs
src/logging.rs
src/manager.rs
src/metrics.rs
src/producer/dummy_producer.rs
src/producer/kafka_producer.rs
src/producer/vector_producer.rs
src/scheduler.rs
src/types/check_config.rs

1. `expect` ought to be called with the reason we think the preceding call will not fail; update our usages accordingly
2. Prefer `expect` over `unwrap`, as the additional context/reasoning of `expect` is helpful

ref(uptime): clean up unwrap/expect usage

---

src/check_config_provider/redis_config_provider.rs
src/check_executor.rs
src/checker/isahc_checker.rs
src/checker/reqwest_checker.rs
src/scheduler.rs

std::time::Instant::now() is guaranteed to be monotonic, whereas Utc::now() can time-travel a bit.
Also, when we must do `to_std` or `checked_sub` with Utc times, provide a default (0) if the subtraction fails due to the aforementioned time-travel.

ref(uptime): use stdtime over chrono for interval timing

---

src/check_executor.rs

In preparation for more changes; plus, it's a little easier to reason about.  Also, always instrument the resulting future.  (This is actually vital, as we otherwise start running into awful type problems with differently-typed futures being returned from the, but also, it's what we run in prod.)

ref(uptime): factor check_executor_loop

---

src/app/config.rs
src/check_config_provider/redis_config_provider.rs
src/check_executor.rs
src/checker.rs
src/checker/dummy_checker.rs
src/checker/isahc_checker.rs
src/checker/reqwest_checker.rs
src/config_waiter.rs
src/manager.rs
src/producer/kafka_producer.rs
src/producer/vector_producer.rs
src/scheduler.rs
src/types/result.rs

At the cost of some unfreeable memory (which won't be freed until the program shuts down, anyway) we avoid making string clones/heap allocations, especially in the inner scheduler and executor loops.

ref(uptime): leak region string to avoid many allocations

---

Cargo.toml
Dockerfile
Dockerfile.localdev
build.rs
src/app.rs
src/check_config_provider/redis_config_provider.rs
src/checker/isahc_checker.rs
src/checker/reqwest_checker.rs
src/manager.rs
src/types/check_config.rs

Bumps the Rust version to 1.85 and fixes the new lints.
Needed for #324

chore: bump Rust toolchain version to 1.85

---

.github/workflows/image.yml

Building with the matrix strategy is causing us to stomp on the cache a bit. This adds a scope parameter so the architectures have different caches.

gha: scope docker cache to platform

---

Dockerfile

- Adds ca-certificates package to the production Docker image to fix TLS certificate verification failures
- Ensures the certificates are upgraded to the latest version during build
The uptime-checker was failing with "tls_error - certificate verify failed" errors for some HTTPS sites. Investigation revealed that the production Dockerfile was missing the `ca-certificates` package, which meant the container had no root CA certificates to validate SSL/TLS connections against.
This particularly affected sites using newer certificate chains (like those from Cloudflare using SSL.com intermediate certificates) that weren't included in the base Alpine image.
Added `ca-certificates` to the package installation in the production Dockerfile and ensured it's upgraded to the latest version. This …

fix(docker): Add ca-certificates to production image

---

Dockerfile

- Moves ca-certificates installation to a separate layer after the binary COPY
- Ensures ca-certificates get updated whenever the application binary changes
Previously, ca-certificates were installed early in the Dockerfile, which meant they only got updated when the base image or earlier layers changed. This could lead to outdated CA certificates causing TLS verification failures.
- Split the RUN command to install base dependencies first (tini, libgcc, curl)
- Install ca-certificates in a separate layer after copying the binary
- This ensures more frequent trust store updates as the binary changes regularly
- Built the Docker image locally and verified ca-certificates are properly installed
- Confirmed the image builds successfully with the new layer ordering

Optimize ca-certificates layer for better updates
