getsentry/uptime-checker

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/cliapp.rs
- src/main.rs
> feat(cli): Add clap

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/main.rs
> feat: Add do nothing tokio

- .github/workflows/validate-pipelines.yml
- .gitignore
- Makefile
- gocd/templates/bash/check-cloudbuild.sh
- gocd/templates/bash/check-github-runs.sh
- gocd/templates/bash/deploy.sh
- gocd/templates/bash/wait-canary.sh
- gocd/templates/jsonnetfile.json
- gocd/templates/jsonnetfile.lock.json
- gocd/templates/pipelines/uptime-checker.libsonnet
- gocd/templates/uptime-checker.jsonnet
Deploys the uptime-checker via gocd
> feat(deploy): Add gocd pipedream pipelines

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/types.rs
This matches what we've defined in the kafka schemas
> feat: Add result types

- .gitignore
Copied the .gitignore from relay and removed irrelevant lines
> chore: More thorough .gitignore

- src/types.rs
> chore: Make types public

- src/cli.rs
- src/cliapp.rs
> ref: Rename Cli to CliApp

- src/scheduler.rs
> fix: Switch back to 5m schedule

- src/checker.rs
- src/producer.rs
- src/types.rs
Uses sentry's TraceId and SpanId types
> feat(tracing): Add span_id

- src/config_store.rs
No need to store a large array type
> ref(config): Remove large array type, just store vec

- src/checker.rs
- src/config_store.rs
- src/producer.rs
- src/scheduler.rs
- src/types/check_config.rs
We'll need tihs once we start firing off requests from the ConfigStore
> ref(checker): Accept CheckConfig in checker

- src/config_store.rs
- src/scheduler.rs
- src/types/check_config.rs
This matches the type provided by arroyo
> ref: Use u16 for partition index

- src/config_store.rs
This adds a `update_partitions` method the allows the config store to be told what partitions we are responsible for. This method will automatically drop partitions that we become no longer responsible for.
> feat: Make ConfigStore aware of known partitions

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/config_consumer.rs
- src/main.rs
This consumer reads config messages from the uptime-configs topic and
registers them in the ConfigStore
> feat: Add config consumer

- src/checker.rs
- src/producer.rs
- src/scheduler.rs
Will allow us to write tests for this code using a mock / noop checker and producer
> ref: Extract scheduler_loop function with trait impl params

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/app/config.rs
- src/main.rs
- src/metrics.rs
Will talk with dogstatsd in production
> feat: Add statsd metrics recorder

- src/checker/http_checker.rs
- src/config_consumer.rs
Want to see if this creates sentry traces or what
> feat: Add a few tracing instrumentations

- src/scheduler.rs
- Check duration
- Checks per bucket
- Check status
- Check failure reason
Part of https://github.com/getsentry/uptime-checker/issues/98
> feat(metris): Record a number of metrics

- src/checker/http_checker.rs
We're not sure that all urls are going to support HEAD, or that a success from HEAD means the GET would be successful. So just remove those checks
> feat(uptime): Remove HEAD checks from checker

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/config_consumer.rs
- src/config_store.rs
- src/manager.rs
- src/scheduler.rs
Adds a lot of tests to the refactor work from https://github.com/getsentry/uptime-checker/pull/108, and fixes various bugs
> Changes and fixes to get refactor working

- src/manager.rs
Follow up from this comment https://github.com/getsentry/uptime-checker/pull/135#discussion_r1702390955
> ref: Don't expose the PartitionedService join handle

- src/check_executor.rs
- src/scheduler.rs
Will add a test for this, but wanted to get it up for eyes first
> feat: Add task to wait for tick completion in order

- src/checker/http_checker.rs
Matches what we did over here https://github.com/getsentry/sentry/pull/75673
> feat: Add user agent for checks

- src/types/check_config.rs
Allows the check config to include additional properties for executing
the config. These are not yet read by the actual check executor
> feat: Add request{method,headers,body} to CheckConfig

- src/checker/http_checker.rs
Reverts getsentry/uptime-checker#164
> Revert "Enable sampling of spans"

- src/types/check_config.rs
This caused a panic in production
Fixes UPTIME-CHECKER-7
> fix(uptime): Fix bug when active regions are empty

- src/checker/http_checker.rs
handle connection refused errors
> fix: handle connection refused error

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/app/config.rs
- src/metrics.rs
Will allow is to include pod_name and other default tags with our metrics
> feat(metrics): Support default tags in metrics

- src/check_executor.rs
Prior to this queue_size was being recorded as `check_concurrency`,
which wasn't quite right, since we were recording the value when added
into the queue. Add a new metric for `num_running`, which is how many
things are being executed at once. This should never be larger than the
current concurrency limit
> ref(metrics): record num_running along with queue size

- src/producer.rs
- src/producer/vector_producer.rs
> ref(vector): restructure code

- gocd/templates/pipelines/uptime-checker.libsonnet
POPs deployment -- only S4S for now
> feat(gocd): pops gocd deployment

- src/check_config_provider/redis_config_provider.rs
> fix(uptime): Fix cluster mode

- Dockerfile.localdev
- src/check_executor.rs
- src/checker/http_checker.rs
- src/types/result.rs
This reverts commit 4d7c29c6c5deb64f2f350a0cb7319e9249bb48f1.
> Revert "feat(uptime): add new failure types (#221)"

- Cargo.lock
- Cargo.toml
see https://github.com/getsentry/reqwest-uptime/pull/1/commits/df9d761891d3f1abdffe8d01221a047760b21fcc
> feat: increase dns cache size

- src/check_executor.rs
Right now, these are set to 50 micros. Set this to a much higher number of 100ms to see if anything changes
> chore(uptime): Set slow/long thresholds higher

- src/check_executor.rs
We use Sequential Consistent ordering for a couple of atomic accesses in the uptime checker.  These are all for independent counters, so this kind of requirement is overkill; relaxed works just fine, and is more performant.
(See https://doc.rust-lang.org/nomicon/atomics.html for a human-readable discussion around what atomic orderings can do/how they ought to be used.)
> ref(uptime): clean up atomic ordering usage

- src/check_executor.rs
> ref(uptime): use and cache gauge handles

- src/scheduler.rs
We create a task, per-scheduler loop, that simply awaits all the check results.  I don't think we need this: we can easily batch all the futures we are awaiting into a single JoinAll future to be awaited in the redis writer task, and since the redis writer task must process all results in tick order, we aren't wasting time waiting for long futures--we were going to wait for them in the other task, anyway.
> ref(uptime): replace join task with join_all future

- .github/workflows/validate-pipelines.yml
```
devenv pin_gha .github/**/*.yml
```
> ci: Pin action uses

- .github/workflows/image.yml
- .github/workflows/release-ghcr-version-tag.yml
- .github/workflows/release.yml
- scripts/bump-version.sh
Based on https://github.com/getsentry/uptime-checker/pull/322
This is very similar to what was done in taskbroker and vroom.
> ci: Release and image workflows

- .github/workflows/image.yml
- scripts/create-manifest.sh
I _believe_ this should work to ammend the SHA and nightly manifest as multi-platform.
> ci: ammend manifest to combine multi-platform image

- Cargo.lock
- Cargo.toml
- src/checker/reqwest_checker.rs
This reverts commit 625e1fcced49cbbfe1d978f3953793d04dfed100.
> Revert "feat(uptime): send reqwest metrics to datadog (#321)"

- .github/workflows/image.yml
This reverts commit b7df86a022486effc94d205dd1a4721755a58bc6.
> Revert "ci: run self-hosted e2e test (#362)"

- Dockerfile
Let's see if we can bump past the offending 3.20.7 version
> Bump to alpine 3.21.4

- Cargo.lock
- Cargo.toml
- src/checker/reqwest_checker.rs
This reverts commit cee0663b131d7a582ca17595bdd66262e6bfb701.
> Reapply "feat(uptime): add redirect uris and connection start timestamps to stats (#376)"
